import { VIEWPORT_TILE_DIMENSIONS, TILE_SIZE } from '~/constants'
import { Game } from '~/Game'
import { vec2 } from 'gl-matrix'
import * as time from '~/time'
import { Canvas2DRenderer } from '~renderer/Canvas2DRenderer'

const canvas = document.createElement('canvas')
document.body.appendChild(canvas)

const viewportDimensions = vec2.scale(
  vec2.create(),
  VIEWPORT_TILE_DIMENSIONS,
  TILE_SIZE,
)

canvas.width = viewportDimensions[0]
canvas.height = viewportDimensions[1]

const map = {
  playfield: `
....~.........~.........~.........~.........~.........
....~.........~.........~.........~.........~.........
.^..~......^..~......^..~......^..~......^..~......^..
....~.........~.........~.........~.........~.........
....~~~~~~....~~~~~~....~~~~~~....~~~~~~....~~~~~~....
......^.........^.........^.........^.........^.......
.....^^........^^........^^........^^........^^.......
....^^^.......^^^.......^^^.......^^^.......^^^.......
.....^^^.......^^^.......^^^.......^^^.......^^^......
.....^.........^.........^.........^.........^........
....~.........~.........~.........~.........~.........
....~.........~.........~.........~.........~.........
.^..~......^..~......^..~......^..~......^..~......^..
....~.........~.........~.........~.........~.........
....~~~~~~....~~~~~~....~~~~~~....~~~~~~....~~~~~~....
......^.........^.........^.........^.........^.......
.....^^........^^........^^........^^........^^.......
....^^^.......^^^.......^^^.......^^^.......^^^.......
.....^^^.......^^^.......^^^.......^^^.......^^^......
.....^.........^.........^.........^.........^........
....~.........~.........~.........~.........~.........
....~.........~.........~.........~.........~.........

`,
  entities: `
..........
..........
..........
.....t....
.w........
.wwwwwwwww
.w........
.wwwww....
......p...
..........
`,
}

const game = new Game(
  new Canvas2DRenderer(canvas.getContext('2d')),
  map,
  viewportDimensions,
)
let prevFrameTime = time.current()

function gameLoop() {
  requestAnimationFrame(gameLoop)

  const now = time.current()
  const dt = now - prevFrameTime
  prevFrameTime = now

  game.update(dt)
  game.render()
}

gameLoop()
