import { VIEWPORT_TILE_DIMENSIONS, TILE_SIZE } from '~/constants'
import { Game } from '~/Game'
import { vec2 } from 'gl-matrix'

const canvas = document.createElement('canvas')
document.body.appendChild(canvas)

const viewportDimensions = vec2.scale(
  vec2.create(),
  VIEWPORT_TILE_DIMENSIONS,
  TILE_SIZE,
)

canvas.width = viewportDimensions[0]
canvas.height = viewportDimensions[1]

const map = {
  playfield: `
....~.........~.........~.........~.........~.........
....~.........~.........~.........~.........~.........
.^..~......^..~......^..~......^..~......^..~......^..
....~.........~.........~.........~.........~.........
....~~~~~~....~~~~~~....~~~~~~....~~~~~~....~~~~~~....
......^.........^.........^.........^.........^.......
.....^^........^^........^^........^^........^^.......
....^^^.......^^^.......^^^.......^^^.......^^^.......
.....^^^.......^^^.......^^^.......^^^.......^^^......
.....^.........^.........^.........^.........^........
....~.........~.........~.........~.........~.........
....~.........~.........~.........~.........~.........
.^..~......^..~......^..~......^..~......^..~......^..
....~.........~.........~.........~.........~.........
....~~~~~~....~~~~~~....~~~~~~....~~~~~~....~~~~~~....
......^.........^.........^.........^.........^.......
.....^^........^^........^^........^^........^^.......
....^^^.......^^^.......^^^.......^^^.......^^^.......
.....^^^.......^^^.......^^^.......^^^.......^^^......
.....^.........^.........^.........^.........^........
....~.........~.........~.........~.........~.........
....~.........~.........~.........~.........~.........

`,
  entities: `
..........
..........
..........
..........
.w........
.wwww.....
.w........
.w........
......p...
..........
`,
}

/**
 * Return the current timestamp in seconds, with sub-millisecond precision.
 */
const curTimeSeconds = (): number => {
  return window.performance.now() / 1000
}

const ctx = canvas.getContext('2d')
const game = new Game(map, viewportDimensions)
let prevFrameTime = curTimeSeconds()

function gameLoop() {
  requestAnimationFrame(gameLoop)
  const now = curTimeSeconds()
  const dt = now - prevFrameTime
  prevFrameTime = now

  game.update(dt)
  game.render(ctx)
}

gameLoop()
